# Generated by Django 3.1.13 on 2025-03-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
